/**
 * Context generator — writes docs/generated/ from the source of truth.
 *
 *   npm run context:generate    write the files
 *   npm run context:check       verify they match source; exit 1 if not
 *
 * Why this exists: hand-written docs in this repo drifted badly. Three files gave three
 * different answers for SUPPORTED_LANGUAGES and none matched the code. Anything mechanically
 * derivable from source is generated here instead of typed by hand.
 *
 * Why static parsing rather than the Swagger document:
 * app.module.ts uses MongooseModule.forRootAsync, so booting Nest to read
 * SwaggerModule.createDocument requires a live MongoDB. That makes it useless in CI and on a
 * machine without the dev database. Parsing the decorators with the TypeScript compiler API
 * needs no runtime and always works. Cost: no request/response schemas, only the route surface.
 *
 * Output is deterministic — files and symbols are sorted — so diffs stay reviewable.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as ts from 'typescript';

const BACKEND = path.resolve(__dirname, '..');
const REPO = path.resolve(BACKEND, '..');
const OUT_DIR = path.join(REPO, 'docs', 'generated');
const BANNER =
  '<!-- GENERATED by `npm run context:generate` (backend/scripts/generate-context.ts) — do not edit by hand -->';

const HTTP_DECORATORS = ['Get', 'Post', 'Put', 'Delete', 'Patch'];

/** Declarations copied verbatim into contracts.md, by file. */
const CONTRACTS: { file: string; symbols: string[] }[] = [
  {
    file: 'src/services/bulk-ingest.service.ts',
    symbols: [
      'SUPPORTED_LANGUAGES',
      'LANGUAGE_NORMALIZE_MAP',
      'TemplateType',
      'TemplateConfig',
      'TEMPLATE_CONFIGS',
      'WizardConfig',
    ],
  },
  {
    file: 'src/services/bulk-processor.service.ts',
    symbols: [
      'STORAGE_DIR',
      'MAX_ROWS',
      'S3_BUCKET',
      'STALE_CUTOFF_MS',
      'RESUME_COOLDOWN_MS',
      'M1M2_ENGLISH_REGEX',
      'M1M2_SCRIPT_REGEXES',
      'M1M2_ML_COL',
    ],
  },
  { file: 'src/services/asset-pipeline.service.ts', symbols: ['S3_BUCKET'] },
];

const SCHEMA_DIR = 'src/schemas';

// ─────────────────────────────────────────────────────────────────────────────
// helpers
// ─────────────────────────────────────────────────────────────────────────────

function parse(absPath: string): ts.SourceFile {
  return ts.createSourceFile(
    absPath,
    fs.readFileSync(absPath, 'utf8'),
    ts.ScriptTarget.Latest,
    true,
  );
}

function decoratorsOf(node: ts.Node): ts.Decorator[] {
  return (ts.canHaveDecorators(node) ? ts.getDecorators(node) : undefined)?.slice() ?? [];
}

/** `@Foo('bar')` → { name: 'Foo', args: ["'bar'"] } */
function readDecorator(d: ts.Decorator): { name: string; args: string[] } | null {
  const expr = d.expression;
  if (!ts.isCallExpression(expr) || !ts.isIdentifier(expr.expression)) return null;
  return {
    name: expr.expression.text,
    args: expr.arguments.map((a) => a.getText()),
  };
}

function stripQuotes(s: string): string {
  return s.replace(/^['"`]|['"`]$/g, '');
}

function joinRoute(base: string, sub: string): string {
  const b = stripQuotes(base).replace(/^\/|\/$/g, '');
  const s = stripQuotes(sub).replace(/^\/|\/$/g, '');
  return '/v1/' + [b, s].filter(Boolean).join('/');
}

function listFiles(relDir: string, suffix = '.ts'): string[] {
  const abs = path.join(BACKEND, relDir);
  if (!fs.existsSync(abs)) return [];
  return fs
    .readdirSync(abs)
    .filter((f) => f.endsWith(suffix) && !f.endsWith('.spec.ts'))
    .sort()
    .map((f) => path.join(relDir, f));
}

// ─────────────────────────────────────────────────────────────────────────────
// routes
// ─────────────────────────────────────────────────────────────────────────────

type Route = {
  method: string;
  route: string;
  handler: string;
  file: string;
  roles: string;
};

function extractRoutes(): Route[] {
  const files = [...listFiles('src/controllers'), 'src/app.controller.ts'].filter((f) =>
    fs.existsSync(path.join(BACKEND, f)),
  );

  const routes: Route[] = [];

  for (const rel of files.sort()) {
    const sf = parse(path.join(BACKEND, rel));

    sf.forEachChild((node) => {
      if (!ts.isClassDeclaration(node)) return;

      const ctrl = decoratorsOf(node)
        .map(readDecorator)
        .find((d) => d?.name === 'Controller');
      if (!ctrl) return;

      const base = ctrl.args[0] ?? '';
      const classRoles = decoratorsOf(node)
        .map(readDecorator)
        .filter((d) => d?.name === 'Roles')
        .flatMap((d) => d!.args.map(stripQuotes));

      for (const member of node.members) {
        if (!ts.isMethodDeclaration(member)) continue;
        const decs = decoratorsOf(member).map(readDecorator);

        const http = decs.find((d) => d && HTTP_DECORATORS.includes(d.name));
        if (!http) continue;

        const methodRoles = decs
          .filter((d) => d?.name === 'Roles')
          .flatMap((d) => d!.args.map(stripQuotes));
        const roles = [...new Set([...classRoles, ...methodRoles])];

        routes.push({
          method: http.name.toUpperCase(),
          route: joinRoute(base, http.args[0] ?? ''),
          handler: member.name.getText(),
          file: rel,
          roles: roles.length ? roles.join(', ') : '—',
        });
      }
    });
  }

  return routes.sort(
    (a, b) => a.route.localeCompare(b.route) || a.method.localeCompare(b.method),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// contracts
// ─────────────────────────────────────────────────────────────────────────────

/** Find a top-level declaration by name and return its source text. */
function findDeclaration(sf: ts.SourceFile, name: string): string | null {
  let out: string | null = null;

  const visit = (node: ts.Node) => {
    if (out) return;
    if (
      (ts.isTypeAliasDeclaration(node) || ts.isInterfaceDeclaration(node)) &&
      node.name.text === name
    ) {
      out = node.getText();
      return;
    }
    if (ts.isVariableStatement(node)) {
      for (const d of node.declarationList.declarations) {
        if (ts.isIdentifier(d.name) && d.name.text === name) {
          out = node.getText();
          return;
        }
      }
    }
    ts.forEachChild(node, visit);
  };

  ts.forEachChild(sf, visit);
  return out;
}

/** Mongoose schema classes → their @Prop-decorated field names and declared types. */
function extractSchemas(): { file: string; cls: string; fields: string[] }[] {
  const out: { file: string; cls: string; fields: string[] }[] = [];

  for (const rel of listFiles(SCHEMA_DIR)) {
    const sf = parse(path.join(BACKEND, rel));

    sf.forEachChild((node) => {
      if (!ts.isClassDeclaration(node) || !node.name) return;
      const isSchema = decoratorsOf(node)
        .map(readDecorator)
        .some((d) => d?.name === 'Schema');
      if (!isSchema) return;

      const fields: string[] = [];
      for (const m of node.members) {
        if (!ts.isPropertyDeclaration(m)) continue;
        const hasProp = decoratorsOf(m)
          .map(readDecorator)
          .some((d) => d?.name === 'Prop');
        if (!hasProp) continue;
        const optional = m.questionToken ? '?' : '';
        const type = m.type ? m.type.getText().replace(/\s+/g, ' ') : 'unknown';
        fields.push(`${m.name.getText()}${optional}: ${type}`);
      }

      out.push({ file: rel, cls: node.name.text, fields });
    });
  }

  return out.sort((a, b) => a.cls.localeCompare(b.cls));
}

/**
 * The coupling that actually broke: the backend language list and the frontend Language
 * union must agree. Compared here so a mismatch shows up in the generated output.
 */
function compareLanguageMirror(): { backend: string[]; frontend: string[]; inSync: boolean } {
  const beSrc = fs.readFileSync(
    path.join(BACKEND, 'src/services/bulk-ingest.service.ts'),
    'utf8',
  );
  const beMatch = beSrc.match(/SUPPORTED_LANGUAGES\s*=\s*\[([^\]]*)\]/);
  const backend = (beMatch?.[1] ?? '')
    .split(',')
    .map((s) => stripQuotes(s.trim()))
    .filter(Boolean)
    .sort();

  const fePath = path.join(REPO, 'frontend/src/types/index.ts');
  let frontend: string[] = [];
  if (fs.existsSync(fePath)) {
    const feMatch = fs
      .readFileSync(fePath, 'utf8')
      .match(/export type Language\s*=\s*([^\n]+)/);
    frontend = (feMatch?.[1] ?? '')
      .split('|')
      .map((s) => stripQuotes(s.trim().replace(/;$/, '')))
      .filter(Boolean)
      .sort();
  }

  return {
    backend,
    frontend,
    inSync: backend.length > 0 && backend.join(',') === frontend.join(','),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// rendering
// ─────────────────────────────────────────────────────────────────────────────

function renderApiSurface(routes: Route[]): string {
  const byFile = new Map<string, Route[]>();
  for (const r of routes) {
    if (!byFile.has(r.file)) byFile.set(r.file, []);
    byFile.get(r.file)!.push(r);
  }

  const lines = [
    BANNER,
    '',
    '# API surface',
    '',
    `**${routes.length} routes** across ${byFile.size} controllers. Base path \`/v1\` (set in \`main.ts\`).`,
    '',
    'Extracted from `@Controller` / `@Get` / `@Post` / `@Put` / `@Delete` / `@Patch` decorators.',
    'Request and response schemas are not captured — run the app and read Swagger at `/api` for those.',
    '',
    'The `Roles` column shows `@Roles(...)` found on the class or method. `—` means no role',
    'decorator; it does **not** mean the route is public — `auth.guard.ts` applies separately.',
    '',
  ];

  for (const file of [...byFile.keys()].sort()) {
    lines.push(`## \`${file}\``, '');
    lines.push('| Method | Route | Handler | Roles |', '|---|---|---|---|');
    for (const r of byFile.get(file)!) {
      lines.push(`| ${r.method} | \`${r.route}\` | \`${r.handler}\` | ${r.roles} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function renderContracts(): string {
  const lines = [BANNER, '', '# Contracts', '', 'Load-bearing declarations, copied from source.', ''];

  const mirror = compareLanguageMirror();
  lines.push('## Language mirror', '');
  lines.push(
    mirror.inSync
      ? `**In sync** — ${mirror.backend.length} languages on both sides: \`${mirror.backend.join(', ')}\``
      : `**OUT OF SYNC** — backend \`${mirror.backend.join(', ')}\` vs frontend \`${mirror.frontend.join(', ')}\``,
  );
  lines.push(
    '',
    'Sources: `backend/src/services/bulk-ingest.service.ts` → `SUPPORTED_LANGUAGES`,',
    '`frontend/src/types/index.ts` → `Language`.',
    '',
  );

  for (const { file, symbols } of CONTRACTS) {
    const abs = path.join(BACKEND, file);
    if (!fs.existsSync(abs)) {
      lines.push(`## \`${file}\``, '', '**File not found.**', '');
      continue;
    }
    const sf = parse(abs);
    lines.push(`## \`backend/${file}\``, '');
    for (const sym of [...symbols].sort()) {
      const text = findDeclaration(sf, sym);
      lines.push(`### \`${sym}\``, '');
      lines.push(text ? '```typescript\n' + text + '\n```' : '**Not found in this file.**');
      lines.push('');
    }
  }

  lines.push('## Mongoose schemas', '');
  for (const s of extractSchemas()) {
    lines.push(`### \`${s.cls}\` — \`backend/${s.file}\``, '');
    lines.push(
      s.fields.length
        ? s.fields.map((f) => `- \`${f}\``).join('\n')
        : '_no `@Prop()` fields found_',
    );
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// reference checking — do the docs still point at things that exist?
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Paths cited in docs that are known-absent on purpose — each is documented in the repo as
 * broken or deleted, so citing it is correct and must not fail the check.
 */
const EXPECTED_MISSING = new Set([
  'src/scripts/bulk_ingest.ts',
  'backend/src/scripts/bulk_ingest.ts',
  'docs/AI_CONTEXT_BULK_UPLOAD.md',
  'docs/FRONTEND_BULK_UPLOAD_ARCHITECTURE.md',
  'docs/context.md',
  'AI_CONTEXT_BULK_UPLOAD.md',
  'FRONTEND_BULK_UPLOAD_ARCHITECTURE.md',
]);

/**
 * Docs excluded from reference checking.
 *
 * `docs/superpowers/` holds design specs, which by their nature discuss files that do not
 * exist yet (planned work), files that were deliberately never created, and files outside the
 * repo entirely. Checking them produces only noise. What must stay true is the documentation
 * agents read as *fact* — CLAUDE.md, docs/decisions/, docs/invariants.md.
 */
const UNCHECKED_DOC_DIRS = ['docs/superpowers'];

const IGNORED_DIRS = new Set(['node_modules', '.git', 'dist', 'coverage']);

/** Every file in the repo, indexed once: by repo-relative path and by bare filename. */
let fileIndex: { paths: Set<string>; names: Set<string> } | null = null;

function indexRepo(): { paths: Set<string>; names: Set<string> } {
  if (fileIndex) return fileIndex;
  const paths = new Set<string>();
  const names = new Set<string>();
  const stack = [REPO];
  while (stack.length) {
    const dir = stack.pop()!;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (IGNORED_DIRS.has(e.name)) continue;
      const abs = path.join(dir, e.name);
      if (e.isDirectory()) stack.push(abs);
      else {
        paths.add(path.relative(REPO, abs).split(path.sep).join('/'));
        names.add(e.name);
      }
    }
  }
  fileIndex = { paths, names };
  return fileIndex;
}

/** Every symbol-ish token appearing in the source trees, indexed once. */
let symbolIndex: Set<string> | null = null;

function indexSymbols(): Set<string> {
  if (symbolIndex) return symbolIndex;
  const found = new Set<string>();
  const stack = [path.join(REPO, 'backend/src'), path.join(REPO, 'frontend/src')];
  while (stack.length) {
    const dir = stack.pop()!;
    if (!fs.existsSync(dir)) continue;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (IGNORED_DIRS.has(e.name)) continue;
      const abs = path.join(dir, e.name);
      if (e.isDirectory()) stack.push(abs);
      else if (/\.(ts|tsx)$/.test(e.name)) {
        for (const tok of fs.readFileSync(abs, 'utf8').match(/[A-Za-z_][A-Za-z0-9_]*/g) ?? [])
          found.add(tok);
      }
    }
  }
  symbolIndex = found;
  return symbolIndex;
}

function docFiles(): string[] {
  const out: string[] = [];
  const claude = path.join(REPO, 'CLAUDE.md');
  if (fs.existsSync(claude)) out.push(claude);

  const walk = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs
      .readdirSync(dir, { withFileTypes: true })
      .sort((a, b) => a.name.localeCompare(b.name))) {
      const p = path.join(dir, e.name);
      const rel = path.relative(REPO, p).split(path.sep).join('/');
      if (UNCHECKED_DOC_DIRS.some((d) => rel.startsWith(d))) continue;
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.md') && !rel.startsWith('docs/generated')) out.push(p);
    }
  };
  walk(path.join(REPO, 'docs'));
  return out;
}

/** A citation resolves if it matches a repo-relative path, or is a bare filename that exists. */
function resolveCited(p: string): boolean {
  const { paths, names } = indexRepo();
  const norm = p.replace(/^\.\//, '');
  if (paths.has(norm)) return true;
  for (const prefix of ['backend/', 'backend/src/', 'frontend/', 'docs/']) {
    if (paths.has(prefix + norm)) return true;
  }
  for (const known of paths) {
    if (known.endsWith('/' + norm)) return true;
  }
  return names.has(path.basename(norm));
}

function checkReferences(): string[] {
  const problems: string[] = [];
  const pathRe = /`([A-Za-z0-9_./-]+\.(?:ts|tsx|md|json|example|yml))`/g;
  const symRe = /→ `([A-Za-z_][A-Za-z0-9_]*)`/g;
  const symbols = indexSymbols();

  for (const doc of docFiles()) {
    const text = fs.readFileSync(doc, 'utf8');
    const rel = path.relative(REPO, doc).split(path.sep).join('/');

    for (const m of text.matchAll(pathRe)) {
      const cited = m[1];
      if (EXPECTED_MISSING.has(cited)) continue;
      if (resolveCited(cited)) continue;
      // A leading dot with no directory part and no match on disk is prose naming a file
      // *extension* (".spec.ts", ".d.ts"), not a path. Real dotfiles such as ".env.example"
      // resolve above and never reach here.
      if (cited.startsWith('.') && !cited.includes('/')) continue;
      problems.push(`${rel}: path does not exist — \`${cited}\``);
    }

    for (const m of text.matchAll(symRe)) {
      if (!symbols.has(m[1]))
        problems.push(`${rel}: symbol not found in source — \`${m[1]}\``);
    }
  }

  return [...new Set(problems)].sort();
}

// ─────────────────────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────────────────────

function build(): Record<string, string> {
  return {
    'api-surface.md': renderApiSurface(extractRoutes()),
    'contracts.md': renderContracts(),
  };
}

function main() {
  const check = process.argv.includes('--check');
  const built = build();
  let failed = false;

  if (check) {
    for (const [name, content] of Object.entries(built)) {
      const abs = path.join(OUT_DIR, name);
      if (!fs.existsSync(abs)) {
        console.error(`STALE  docs/generated/${name} is missing`);
        failed = true;
      } else if (fs.readFileSync(abs, 'utf8') !== content) {
        console.error(`STALE  docs/generated/${name} does not match source`);
        failed = true;
      } else {
        console.log(`ok     docs/generated/${name}`);
      }
    }

    const problems = checkReferences();
    if (problems.length) {
      console.error(`\nBroken references (${problems.length}):`);
      for (const p of problems) console.error(`  ${p}`);
      failed = true;
    } else {
      console.log('ok     all cited paths and symbols resolve');
    }

    const mirror = compareLanguageMirror();
    if (!mirror.inSync) {
      console.error(
        `\nLanguage mirror OUT OF SYNC: backend [${mirror.backend}] vs frontend [${mirror.frontend}]`,
      );
      failed = true;
    } else {
      console.log('ok     language mirror in sync');
    }

    if (failed) {
      console.error('\nRun `npm run context:generate` and commit the result.');
      process.exit(1);
    }
    console.log('\ncontext:check passed');
    return;
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, content] of Object.entries(built)) {
    fs.writeFileSync(path.join(OUT_DIR, name), content);
    console.log(`wrote  docs/generated/${name}`);
  }

  const problems = checkReferences();
  if (problems.length) {
    console.log(`\nnote: ${problems.length} broken doc reference(s) — not fatal here, fatal in check:`);
    for (const p of problems) console.log(`  ${p}`);
  }
}

main();
