var common_config = {
  contentLevel: [
    {
      level: 'L1',
      syllableCount: { $eq: 2 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'L1',
      wordCount: { $gte: 2, $lte: 3 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'L2',
      syllableCount: { $gte: 2, $lte: 3 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'L2',
      wordCount: { $gte: 2, $lte: 3 },
      syllableCount: { $lte: 8 },
      syllableCountArray: {
        $not: {
          $elemMatch: {
            v: { $gte: 4 },
          },
        },
      },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'L3',
      syllableCount: { $gte: 4 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'L3',
      wordCount: { $gt: 2, $lte: 5 },
      syllableCount: { $lte: 15 },
      language: 'ta',
      syllableCountArray: {
        $not: {
          $elemMatch: {
            v: { $gte: 5 },
          },
        },
      },
      contentType: 'Sentence',
    },
    {
      level: 'L3',
      wordCount: { $lte: 10 },
      language: 'ta',
      contentType: 'Paragraph',
    },
    {
      level: 'L4',
      wordCount: { $gt: 5, $lte: 7 },
      syllableCount: { $lte: 20 },
      language: 'ta',
      syllableCountArray: {
        $not: {
          $elemMatch: {
            v: { $gte: 7 },
          },
        },
      },
      contentType: 'Sentence',
    },
    {
      level: 'L4',
      wordCount: { $lte: 10 },
      language: 'ta',
      contentType: 'Paragraph',
    },
    {
      level: 'L5',
      wordCount: { $gte: 7, $lte: 10 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'L5',
      wordCount: { $gt: 10, $lte: 15 },
      language: 'ta',
      contentType: 'Paragraph',
    },
    {
      level: 'L6',
      wordCount: { $gte: 7, $lte: 12 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'L6',
      wordCount: { $gt: 15 },
      language: 'ta',
      contentType: 'Paragraph',
    },
  ],
  complexity: [
    {
      level: 'C1',
      totalOrthoComplexity: { $gte: 0, $lte: 2 },
      totalPhonicComplexity: { $gte: 0, $lte: 30 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C1',
      totalOrthoComplexity: { $gte: 0, $lte: 75 },
      totalPhonicComplexity: { $gte: 0, $lte: 20 },
      meanComplexity: { $gte: 0, $lte: 50 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'C2',
      totalOrthoComplexity: { $gte: 0, $lte: 8 },
      totalPhonicComplexity: { $gte: 0, $lte: 60 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C2',
      totalOrthoComplexity: { $gte: 0, $lte: 20 },
      totalPhonicComplexity: { $gte: 0, $lte: 100 },
      meanComplexity: { $gte: 0, $lte: 50 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'C3',
      totalOrthoComplexity: { $gte: 0, $lte: 15 },
      totalPhonicComplexity: { $gte: 0, $lte: 100 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C3',
      totalOrthoComplexity: { $gte: 20, $lte: 50 },
      totalPhonicComplexity: { $lte: 200 },
      meanComplexity: { $gte: 50, $lte: 100 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'C4',
      totalOrthoComplexity: { $gt: 15 },
      totalPhonicComplexity: { $gt: 100 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C4',
      totalOrthoComplexity: { $gt: 50 },
      totalPhonicComplexity: { $gt: 200 },
      meanComplexity: { $gt: 100 },
      language: 'ta',
      contentType: 'Sentence',
    },
  ],
  readingComplexity: [
    {
      level: 'C0',
      readingComplexity: { $lt: 1 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C1',
      readingComplexity: { $gte: 1, $lte: 8 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C1',
      readingComplexity: { $lte: 12 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'C2',
      readingComplexity: { $lt: 15 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C2',
      language: 'ta',
      readingComplexity: { $lte: 30 },
      contentType: 'Sentence',
    },
    {
      level: 'C3',
      readingComplexity: { $lte: 20 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C3',
      readingComplexity: { $lte: 50 },
      language: 'ta',
      contentType: 'Sentence',
    },
    {
      level: 'C4',
      readingComplexity: { $gt: 20 },
      language: 'ta',
      contentType: 'Word',
    },
    {
      level: 'C4',
      readingComplexity: { $gt: 50 },
      language: 'ta',
      contentType: 'Sentence',
    },
  ],
  readingComplexityLang : ['hi','te','kn'],
  tags: [
    'CEFR_M1_P1',
    'CEFR_M1_P2',
    'CEFR_M1_P3',
    'CEFR_M1_P4',
    'CEFR_M1_S1',
    'CEFR_M1_S2',
    'CEFR_M2_P1',
    'CEFR_M2_P2',
    'CEFR_M2_P3',
    'CEFR_M2_P4',
    'CEFR_M2_S1',
    'CEFR_M2_S2',
    'CEFR_M3_P1',
    'CEFR_M3_P2',
    'CEFR_M3_P3',
    'CEFR_M3_P4',
    'CEFR_M3_S1',
    'CEFR_M3_S2',
    'CEFR_R1_P1',
    'CEFR_R1_P2',
    'CEFR_R1_P3',
    'CEFR_R1_P4',
    'CEFR_R1_P5',
    'CEFR_R1_P6',
    'CEFR_R1_P7',
    'CEFR_R1_P8',
    'CEFR_R1_P9',
    'CEFR_R1_P10',
    'CEFR_R1_P11',
    'CEFR_R1_P12',
    'CEFR_R1_P13',
    'CEFR_R1_P14',
    'CEFR_R1_P15',
    'CEFR_R2_P1',
    'CEFR_R2_P2',
    'CEFR_R2_P3',
    'CEFR_R2_P4',
    'CEFR_R2_P5',
    'CEFR_R2_P6',
    'CEFR_R2_P7',
    'CEFR_R2_P8',
    'CEFR_R2_P9',
    'CEFR_R2_P10',
    'CEFR_R2_P11',
    'CEFR_R2_P12',
    'CEFR_R2_P13',
    'CEFR_R2_P14',
    'CEFR_R2_P15',
    'CEFR_M1_L1',
    'CEFR_M1_L2',
    'CEFR_M1_L3',
    'CEFR_M1_L4',
    'CEFR_M2_L1',
    'CEFR_M2_L2',
    'CEFR_M2_L3',
    'CEFR_M2_L4',
    'CEFR_M3_L1',
    'CEFR_M3_L2',
    'CEFR_M3_L3',
    'CEFR_M3_L4'
]

};

export default common_config;
