name: Deploy Dev - All Content Service

on:
  push:
    branches:
      - lais-v3.0.3

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export BRANCH=lais-v2.2
            cd /home/${{ secrets.USERNAME }}/git/all-content-service
            ./deploy.sh
